(function(){'use strict';if(window.selfhost_auth_loaded)return;window.selfhost_auth_loaded=true;
var ORIGIN=location.protocol+'//'+location.host,csrf='',current=null,polling=false;
function api(path,opt){opt=opt||{};opt.credentials='same-origin';opt.headers=Object.assign({'Content-Type':'application/json'},opt.headers||{});if(csrf)opt.headers['X-CSRF-Token']=csrf;return fetch(ORIGIN+path,opt).then(function(r){if(r.status===401){location.replace('/account/?gate=1');var unauthorized=Error('Требуется вход');unauthorized.status=401;throw unauthorized}if(r.status===204)return null;return r.json().catch(function(){return{}}).then(function(j){if(!r.ok){var error=Error(j.message||'Ошибка');error.status=r.status;throw error}return j.data})})}
function style(){if(document.getElementById('selfhost-style'))return;var s=document.createElement('style');s.id='selfhost-style';s.textContent='#selfhost-pair{position:fixed;inset:0;z-index:999999;background:#090b0eef;display:flex;align-items:center;justify-content:center;padding:4vw}.selfhost-box{width:min(1100px,100%);background:#171a20;border-radius:28px;padding:3em;display:grid;grid-template-columns:1fr 330px;gap:3em;color:#fff}.selfhost-box h1{font-size:3em;margin:.1em 0}.selfhost-box p{color:#b4bac4;font-size:1.2em}.selfhost-qr{background:#fff;padding:14px;border-radius:18px}.selfhost-qr svg{display:block;width:100%;height:auto}.selfhost-code{font:700 2.4em monospace;letter-spacing:.2em}.selfhost-status{padding:.8em 1em;border-radius:12px;background:#303640;margin:1em 0}.selfhost-status.error{background:#3b1d22;color:#ffb8bd}.selfhost-close{padding:1em 1.4em;background:#303640;border-radius:14px;display:inline-block}@media(max-width:700px){.selfhost-box{grid-template-columns:1fr;padding:1.5em}.selfhost-box h1{font-size:2em}.selfhost-qr{max-width:260px}}';document.head.appendChild(s)}
function close(){polling=false;var e=document.getElementById('selfhost-pair');if(e)e.remove();try{Lampa.Controller.toggle('settings_component')}catch(x){}}
function pairStatus(text,error){var e=document.querySelector('#selfhost-pair .selfhost-status');if(!e)return;e.textContent=text;e.className='selfhost-status'+(error?' error':'')}
function wait(d){if(!polling)return;fetch(ORIGIN+'/api/v1/auth/pairings/'+d.pairingId+'/wait',{credentials:'same-origin',headers:{'X-Pair-Token':d.tvSecret}}).then(function(r){if(r.status===204)return{pending:true};return r.json().catch(function(){return{}}).then(function(j){return{status:r.status,ok:r.ok,data:j}})}).then(function(result){if(!polling)return;if(result.pending)return setTimeout(function(){wait(d)},300);if(result.ok&&result.data&&result.data.data&&result.data.data.authorized){csrf=result.data.data.csrfToken;current=result.data.data.user;close();Lampa.Noty.show('Вход выполнен');return setTimeout(function(){location.reload()},700)}if(result.status===404||result.status===410||(result.status>=400&&result.status<500&&result.status!==429)){polling=false;pairStatus(result.data.message||'QR-вход завершён. Закройте окно и получите новый код.',true);return}setTimeout(function(){wait(d)},1500)}).catch(function(){if(polling)setTimeout(function(){wait(d)},1500)})}
function openPair(){if(document.getElementById('selfhost-pair'))return;style();api('/api/v1/auth/pairings',{method:'POST',body:JSON.stringify({deviceName:(Lampa.Platform&&Lampa.Platform.get?Lampa.Platform.get():'TV')})}).then(function(d){polling=true;var el=document.createElement('div');el.id='selfhost-pair';el.innerHTML='<div class="selfhost-box"><div><div>АККАУНТ LAMPA</div><h1>Вход по QR-коду</h1><p>Откройте камеру на телефоне и наведите на код. После входа телевизор авторизуется автоматически.</p><div class="selfhost-code"></div><p>Или откройте <b>'+ORIGIN+'/account/</b></p><div class="selfhost-status" role="status">Ожидаем вход на телефоне…</div><div class="selfhost-close selector">Закрыть</div></div><div class="selfhost-qr"></div></div>';el.querySelector('.selfhost-code').textContent=d.code;el.querySelector('.selfhost-qr').innerHTML=d.qrSvg;el.querySelector('.selfhost-close').addEventListener('click',close);document.body.appendChild(el);wait(d)}).catch(function(e){if(e.status!==401)Lampa.Noty.show(e.message)})}
 function about(){var box=$('<div style="padding:1.5em;max-width:800px"></div>');box.append($('<img src="/account/tmdb-logo.svg" alt="TMDB" style="width:220px;max-width:60%;height:auto">'));box.append($('<p></p>').text('This product uses the TMDB API but is not endorsed or certified by TMDB.'));box.append($('<p></p>').text('Рецензии, карточки и изображения предоставляются The Movie Database.'));Lampa.Modal.open({title:'О приложении',html:box,onBack:function(){Lampa.Modal.close()}})}
function checkSession(){api('/api/v1/auth/me').then(function(d){current=d.user;csrf=d.csrfToken}).catch(function(e){if(e.status!==401)console.log('SelfHosted auth',e.message)})}
function start(){checkSession();setInterval(checkSession,60000);Lampa.SettingsApi.addComponent({component:'selfhost_account',name:'Аккаунт'});Lampa.SettingsApi.addParam({component:'selfhost_account',param:{type:'button'},field:{name:'Войти по QR-коду'},onChange:openPair});Lampa.SettingsApi.addParam({component:'selfhost_account',param:{type:'button'},field:{name:'Открыть личный кабинет'},onChange:function(){window.open(ORIGIN+'/account/','_blank')}});Lampa.SettingsApi.addParam({component:'selfhost_account',param:{type:'button'},field:{name:'О приложении и TMDB'},onChange:about})}
 window.SelfHostedAuth={api:api,openPairing:openPair,user:function(){return current},csrf:function(){return csrf}};if(window.appready)start();else Lampa.Listener.follow('app',function(e){if(e.type==='ready')start()});
})();
